MyContact/MyContact/MyContact/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from MyContacct import views as contact
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^signup/$', contact.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^contact/$', contact.home, name='home'),
    url(r'^logout/$', contact.logout, name='logout'),
    url(r'^add/$', contact.add, name='add'),
    url(r'^showLogout/$', contact.showLogout, name='showLogout'),
    url(r'^list/$', contact.list, name='list'),
    url(r'^modify/$', contact.modify, name='modify'),
    url(r'^delete/$', contact.delete, name='delete'),
    url(r'^search/$', contact.search, name='search'),
    url(r'^admin/', admin.site.urls),
]

MyContact/MyContact/MyContacct/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

class BookContact(models.Model):
    userId = models.AutoField(primary_key=True)
    userName = models.CharField(max_length=255, blank=True)
    firstName = models.CharField(max_length=255, blank=True)
    lastName = models.CharField(max_length=255, blank=True)
    mobile = models.CharField(max_length=255, blank=True)
    email = models.CharField(max_length=255, blank=True)
    contactAdress = models.CharField(max_length=255, blank=True)
    is_active = models.IntegerField(default=1)

MyContact/MyContact/MyContacct/forms.py
from django import forms

class ContactForm(forms.Form):
    firstName = forms.CharField(required=True)
    lastName = forms.CharField(required=True)
    mobile = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    contactAdress = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

class SearchForm(forms.Form):
    CHOICES = (
                ('1', 'First Name',),
                ('2', 'Last Name',),
                ('3', 'Mobile',),
                ('4', 'Email',),
                ('5', 'Contact Adress',)
    )
    searchCategory = forms.ChoiceField(choices=CHOICES)
    searchString = forms.CharField(required=True)

MyContact/MyContact/MyContacct/views.py
from django.template.loader import get_template
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.middleware import csrf
from .forms import ContactForm, SearchForm
from .models import BookContact
from django.template.context_processors import csrf

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
                return redirect('/login')
            else:
                return redirect('/signup')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def logout(request):
    return redirect('showLogout')

def showLogout (request):
    t = get_template('registration/logout.html')
    html = t.render()
    response = HttpResponse(html)
    response.delete_cookie('user_name')
    return response

def home(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user is not None:
            t = get_template('a1.html')
            html = t.render({'username':username})
            response = HttpResponse(html)
            response.set_cookie('user_name', username)
            return response
        else:
            return HttpResponse("NOT  Valid User")
    else:
        user_name = request.COOKIES['user_name']
        t = get_template('a1.html')
        html = t.render({'username': user_name})
        return HttpResponse(html)

def getUserFromSessions (request):
    SESSION_KEY = '_auth_user_id'
    BACKEND_SESSION_KEY = '_auth_user_backend'
    from django.contrib.auth import load_backend
    user_id = request.session[SESSION_KEY]
    backend_path = request.session[BACKEND_SESSION_KEY]
    backend = load_backend(backend_path)
    return  backend.get_user(user_id)

def search (request):
    form_class = SearchForm
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            searchCategoryID  = request.POST.get( 'searchCategory', '')
            category = [
                        'firstName','lastName',
                        'mobile','email',
                        'contactAdress'
            ]
            searchCategory = category[int(searchCategoryID) - 1]
            searchString = request.POST.get('searchString', '')
            if 'user_name' in request.COOKIES:
                user_name = request.COOKIES['user_name']
                tmp = { }
                tmp [searchCategory + '__contains'] = searchString
                tmp['userName'] = user_name
                tmp['is_active'] = 1
                çontacts = { 'contacts': BookContact.objects.filter(**tmp),'username':request.COOKIES['user_name'] }
                t = get_template('contact_list.html')
                html = t.render(çontacts)
                return HttpResponse(html)
    return render(request, 'search_contact.html', {'form': form_class,'username':request.COOKIES['user_name']})

def add(request):
    form_class = ContactForm
    obj = BookContact()
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            firstName  = request.POST.get( 'firstName', '')
            lastName = request.POST.get('lastName', '')
            mobile  = request.POST.get('mobile', '')
            email = request.POST.get('email', '')
            contactAdress = request.POST.get('contactAdress', '')
            if 'user_name' in request.COOKIES:
                user_name = request.COOKIES['user_name']
                obj = BookContact()
                obj.userName = user_name
                obj.firstName = firstName
                obj.lastName = lastName
                obj.mobile = mobile
                obj.email = email
                obj.contactAdress = contactAdress
                obj.is_active = 1
                obj.save()
                t = get_template('add_confirm.html')
                html = t.render({'message':"add",'username':request.COOKIES['user_name']})
                return HttpResponse(html)
    return render(request, 'contact_add.html', {'form': form_class,'username':request.COOKIES['user_name']})

def list(request):
    user_name = request.COOKIES['user_name']
    çontacts = {
                'contacts': BookContact.objects.filter(userName=user_name,is_active=1),
                'username':request.COOKIES['user_name']
    }
    t = get_template('contact_list.html')
    html = t.render(çontacts)
    return HttpResponse(html)


def modify(request):
    if request.method == 'POST':
        id = request.POST.get('id', '')
        firstName = request.POST.get('firstName', '')
        lastName = request.POST.get('lastName', '')
        mobile = request.POST.get('mobile', '')
        email = request.POST.get('email', '')
        contactAdress = request.POST.get('contactAdress', '')
        çontacts = BookContact.objects.filter().get(userId=id)
        çontacts.firstName = firstName
        çontacts.lastName = lastName
        çontacts.mobile = mobile
        çontacts.email = email
        çontacts.contactAdress = contactAdress
        çontacts.save()
        t = get_template('add_confirm.html')
        html = t.render({'message': "modify",'username':request.COOKIES['user_name']})
        return HttpResponse(html)
    else:
        id = request.GET.get('id', '')
        çontacts =  BookContact.objects.filter().get(userId=id)
        contact = {
            'firstName':çontacts.firstName,
            'lastName':çontacts.lastName,
            'mobile':çontacts.mobile,
            'email':çontacts.email,
            'contactAdress':çontacts.contactAdress,
            'userId':çontacts.userId,
            'csrfmiddlewaretoken': get_or_create_csrf_token(request),
            'username': request.COOKIES['user_name']
        }
        t = get_template('contact_modify.html')
        html = t.render(contact)
        return HttpResponse(html)

def delete(request):
    id = request.GET.get('id', '')
    çontacts = BookContact.objects.filter().get(userId=id)
    çontacts.is_active = 0
    çontacts.save()
    t = get_template('add_confirm.html')
    html = t.render({'message': "delete",'username':request.COOKIES['user_name']})
    return HttpResponse(html)

def get_or_create_csrf_token(request):
    token = request.META.get('CSRF_COOKIE', None)
    if token is None:
        token = csrf._get_new_csrf_key()
        request.META['CSRF_COOKIE'] = token
    request.META['CSRF_COOKIE_USED'] = True
    return token

MyContact/MyContact/MyContacct/templates/a1.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

  Hi {{ username }}!

{% endblock %}

MyContact/MyContact/MyContacct/templates/add_confirm.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% if message == "add"  %}
   Contact Added
 {% elif message == "modify"  %}
  Contact Modified
 {% elif message == "delete"  %}
  Contact deleted
{% endif %}

{% endblock %}

MyContact/MyContact/MyContacct/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}

</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
            <b>My Contact App... </b>
        </div>

        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome, ... ' %}
                <strong>{{ username }}! </strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}

                {% endif %}
                <a href="/logout/">  | Logout | &nbsp</a>
                <a href="http://www.shivaprasad.info">  About Author </a>
            {% endblock %}

        </div>

        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="/contact">Home</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}

        <a href="/add/"> | Add </a>
        <a href="/list/"> | View</a>
        <a href="/search/"> | Search</a>

    </div>

    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear">
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

MyContact/MyContact/MyContacct/templates/base1.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}

</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
            <b> My Contact App... </b>

        </div>

        <div id="user-tools">

            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
            {% endblock %}

        </div>

        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="/login/"> | Login  | </a>
    <a href="http://www.shivaprasad.info">  About Author </a>
    </div>

    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear">
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

MyContact/MyContact/MyContacct/templates/base_backup.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}

    <a href="/login/"> | Login</a>
        <a href="/logout/"> | Logout</a>
    </div>

    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear">
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

MyContact/MyContact/MyContacct/templates/contact_add.html
{% extends 'base.html' %}
{% block content %}
<h1>Contact</h1>
<form role="form" action="/add/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

MyContact/MyContact/MyContacct/templates/contact_list.html
{% extends 'base.html' %}
<table>

        {% block content %}
    <table >
        <tr>
            <td><b>First Name</b></td>
            <td><b>Last Name</b></td>
            <td><b>Phone</b></td>
            <td><b>Email</b></td>
            <td><b>Adress</b></td>
            <td><b>Functions </b></td>
        </tr>
        {% for contact in contacts %}
        <tr>
            <td>{{ contact.firstName }}</td>
            <td>{{ contact.lastName }}</td>
            <td>{{ contact.mobile }}</td>
            <td>{{ contact.email }}</td>
            <td>{{ contact.contactAdress }}</td>
            <td> <div class="dropdown">
  <div class="dropdown-content">
    |<a href="/modify?id={{ contact.userId }}">Modify</a>|
    <a href="/delete?id={{ contact.userId }}">Delete</a>|
  </div></td>
        </tr>
        {% endfor %}
    </table>
        {% endblock %}

</table>

MyContact/MyContact/MyContacct/templates/contact_modify.html
{% extends 'base.html' %}

     {% block content %}

    <form id="name-form" role="form" action="/modify/" method="post">
        <input type='hidden' name='csrfmiddlewaretoken' value='{{csrfmiddlewaretoken}}' />
        <input type='hidden' name='id' value='{{userId}}' />
        <p><label for="id_firstName">Firstname:</label>
            <input type="text" name="firstName" value="{{firstName}}" />
        </p>

        <p><label for="id_lastName">Lastname:</label>
            <input type="text" name="lastName" value="{{lastName}}"/>
        </p>

        <p><label for="id_mobile">Mobile:</label>
            <input type="text" name="mobile" value="{{mobile}}" />
        </p>

        <p><label for="id_email">Email:</label>
            <input type="email" name="email" value="{{email}}" />
        </p>

        <p><label for="id_contactAdress">Contactadress:</label>
            <textarea name="contactAdress" cols="40" rows="10">
                {{contactAdress}}
            </textarea>
        </p>
        <button type="submit">Submit</button>
    </form>
        {% endblock %}

MyContact/MyContact/MyContacct/templates/search_contact.html
{% extends 'base.html' %}
{% block content %}
<h1>Contact</h1>
<form role="form" action="/search/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

MyContact/MyContact/MyContacct/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}